//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalePlusDatos.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAJES_LEIDOS
    {
        public int ID_CHAT { get; set; }
        public int ID_USUARIO { get; set; }
        public System.DateTime TIEMPO { get; set; }
        public Nullable<bool> LEIDO { get; set; }
        public int ID_MENSAJE { get; set; }
    
        public virtual CHATS CHATS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
