//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalePlusDatos.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ROYALEPLUSEntities : DbContext
    {
        public ROYALEPLUSEntities()
            : base("name=ROYALEPLUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHATS> CHATS { get; set; }
        public virtual DbSet<MENSAJES> MENSAJES { get; set; }
        public virtual DbSet<MENSAJES_LEIDOS> MENSAJES_LEIDOS { get; set; }
        public virtual DbSet<PARTICIPANTES> PARTICIPANTES { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    
        public virtual int PA_INSERTAR_MENSAJE(Nullable<int> iD_CHAT, Nullable<int> iD_USUARIO, string cUERPO_MENSAJE, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_CHATParameter = iD_CHAT.HasValue ?
                new ObjectParameter("ID_CHAT", iD_CHAT) :
                new ObjectParameter("ID_CHAT", typeof(int));
    
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var cUERPO_MENSAJEParameter = cUERPO_MENSAJE != null ?
                new ObjectParameter("CUERPO_MENSAJE", cUERPO_MENSAJE) :
                new ObjectParameter("CUERPO_MENSAJE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERTAR_MENSAJE", iD_CHATParameter, iD_USUARIOParameter, cUERPO_MENSAJEParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_LOGIN(string nOMBRE, string cONTRASENNA, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cONTRASENNAParameter = cONTRASENNA != null ?
                new ObjectParameter("CONTRASENNA", cONTRASENNA) :
                new ObjectParameter("CONTRASENNA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_LOGIN", nOMBREParameter, cONTRASENNAParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO(string iD_USUARIO, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO", iD_USUARIOParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO2(string iD_USUARIO, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO2", iD_USUARIOParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO3(string iD_USUARIO, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO3", iD_USUARIOParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO4(string iD_USUARIO, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO4", iD_USUARIOParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO5(string iD_USUARIO, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO5", iD_USUARIOParameter, rETCODE, mENSAJE);
        }
    
        public virtual ObjectResult<PA_OBTENER_CHATS> PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO6(string iD_USUARIO, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_OBTENER_CHATS>("PA_OBTENER_TODOS_CHATS_DE_UN_USUARIO6", iD_USUARIOParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_ACTUALIZAR_ULTIMA_CONEXION(Nullable<int> iD_USUARIO, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ACTUALIZAR_ULTIMA_CONEXION", iD_USUARIOParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_OBTENER_100_MENSAJES_DE_UN_CHAT(Nullable<int> gRUPO, Nullable<int> iD_CHAT, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var gRUPOParameter = gRUPO.HasValue ?
                new ObjectParameter("GRUPO", gRUPO) :
                new ObjectParameter("GRUPO", typeof(int));
    
            var iD_CHATParameter = iD_CHAT.HasValue ?
                new ObjectParameter("ID_CHAT", iD_CHAT) :
                new ObjectParameter("ID_CHAT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_OBTENER_100_MENSAJES_DE_UN_CHAT", gRUPOParameter, iD_CHATParameter, rETCODE, mENSAJE);
        }
    
        public virtual ObjectResult<PA_OBTENER_100_MENSAJES> PA_OBTENER_100_MENSAJES_DE_UN_CHAT1(Nullable<int> gRUPO, Nullable<int> iD_CHAT, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var gRUPOParameter = gRUPO.HasValue ?
                new ObjectParameter("GRUPO", gRUPO) :
                new ObjectParameter("GRUPO", typeof(int));
    
            var iD_CHATParameter = iD_CHAT.HasValue ?
                new ObjectParameter("ID_CHAT", iD_CHAT) :
                new ObjectParameter("ID_CHAT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_OBTENER_100_MENSAJES>("PA_OBTENER_100_MENSAJES_DE_UN_CHAT1", gRUPOParameter, iD_CHATParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_OBTENER_MENSAJES_NUEVOS(Nullable<int> iD_CHAT, Nullable<int> iD_MENSAJE, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_CHATParameter = iD_CHAT.HasValue ?
                new ObjectParameter("ID_CHAT", iD_CHAT) :
                new ObjectParameter("ID_CHAT", typeof(int));
    
            var iD_MENSAJEParameter = iD_MENSAJE.HasValue ?
                new ObjectParameter("ID_MENSAJE", iD_MENSAJE) :
                new ObjectParameter("ID_MENSAJE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_OBTENER_MENSAJES_NUEVOS", iD_CHATParameter, iD_MENSAJEParameter, rETCODE, mENSAJE);
        }
    
        public virtual ObjectResult<PA_OBTENER_100_MENSAJES> PA_OBTENER_MENSAJES_NUEVOS1(Nullable<int> iD_CHAT, Nullable<int> iD_MENSAJE, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_CHATParameter = iD_CHAT.HasValue ?
                new ObjectParameter("ID_CHAT", iD_CHAT) :
                new ObjectParameter("ID_CHAT", typeof(int));
    
            var iD_MENSAJEParameter = iD_MENSAJE.HasValue ?
                new ObjectParameter("ID_MENSAJE", iD_MENSAJE) :
                new ObjectParameter("ID_MENSAJE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_OBTENER_100_MENSAJES>("PA_OBTENER_MENSAJES_NUEVOS1", iD_CHATParameter, iD_MENSAJEParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_MARCAR_TODOS_COMO_LEIDOS(Nullable<int> iD_CHAT, Nullable<int> iD_USUARIO, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_CHATParameter = iD_CHAT.HasValue ?
                new ObjectParameter("ID_CHAT", iD_CHAT) :
                new ObjectParameter("ID_CHAT", typeof(int));
    
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MARCAR_TODOS_COMO_LEIDOS", iD_CHATParameter, iD_USUARIOParameter, rETCODE, mENSAJE);
        }
    }
}
