//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalePlusDatos.BD
{
    using System;
    
    public partial class PA_OBTENER_100_MENSAJES
    {
        public int ID_MENSAJE { get; set; }
        public int ID_CHAT { get; set; }
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public System.DateTime TIEMPO { get; set; }
        public bool LEIDO { get; set; }
        public string MENSAJE { get; set; }
    }
}
