//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalePlusDatos.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTICIPANTES()
        {
            this.MENSAJES = new HashSet<MENSAJES>();
        }
    
        public int ID_CHAT { get; set; }
        public int ID_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAJES> MENSAJES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
